
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Point;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ayush Wadhwa
 */
public class UI extends javax.swing.JFrame {

    /**
     * Creates new form UI
     */
    public UI() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        outerWrapper = new javax.swing.JPanel();
        innerWrapper = new javax.swing.JPanel();
        loginGif = new javax.swing.JLabel();
        loginL = new javax.swing.JLabel();
        pswdL = new javax.swing.JLabel();
        usernameL = new javax.swing.JLabel();
        usenameTF = new javax.swing.JTextField();
        passwordFT = new javax.swing.JPasswordField();
        loginBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(null);
        setMinimumSize(new java.awt.Dimension(600, 400));

        outerWrapper.setBackground(new java.awt.Color(255, 102, 51));

        innerWrapper.setBackground(new java.awt.Color(42, 43, 46));

        loginGif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login.gif"))); // NOI18N

        loginL.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 26)); // NOI18N
        loginL.setForeground(new java.awt.Color(247, 247, 242));
        loginL.setText("Login");

        pswdL.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 28)); // NOI18N
        pswdL.setForeground(new java.awt.Color(247, 247, 242));
        pswdL.setText("Password");

        usernameL.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 28)); // NOI18N
        usernameL.setForeground(new java.awt.Color(247, 247, 242));
        usernameL.setText("Username");

        usenameTF.setFont(new java.awt.Font("Bahnschrift", 0, 24)); // NOI18N
        usenameTF.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.darkGray, java.awt.Color.white, java.awt.Color.lightGray));
        usenameTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usenameTFActionPerformed(evt);
            }
        });

        passwordFT.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        passwordFT.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.lightGray, java.awt.Color.white, java.awt.Color.lightGray));
        passwordFT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFTActionPerformed(evt);
            }
        });

        loginBtn.setBackground(new java.awt.Color(255, 255, 255));
        loginBtn.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout innerWrapperLayout = new javax.swing.GroupLayout(innerWrapper);
        innerWrapper.setLayout(innerWrapperLayout);
        innerWrapperLayout.setHorizontalGroup(
            innerWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(innerWrapperLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(loginGif, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(innerWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(innerWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(innerWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pswdL, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(usenameTF))
                        .addComponent(usernameL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(passwordFT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, innerWrapperLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(innerWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, innerWrapperLayout.createSequentialGroup()
                        .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(148, 148, 148))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, innerWrapperLayout.createSequentialGroup()
                        .addComponent(loginL, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124))))
        );
        innerWrapperLayout.setVerticalGroup(
            innerWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(innerWrapperLayout.createSequentialGroup()
                .addGroup(innerWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(innerWrapperLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(loginGif, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(innerWrapperLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(loginL, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(usernameL)
                        .addGap(18, 18, 18)
                        .addComponent(usenameTF, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pswdL, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(passwordFT, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(loginBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout outerWrapperLayout = new javax.swing.GroupLayout(outerWrapper);
        outerWrapper.setLayout(outerWrapperLayout);
        outerWrapperLayout.setHorizontalGroup(
            outerWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(innerWrapper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        outerWrapperLayout.setVerticalGroup(
            outerWrapperLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(innerWrapper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(outerWrapper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(outerWrapper, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usenameTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usenameTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usenameTFActionPerformed

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // TODO add your handling code here:
        if((usenameTF.getText().length() >=1) && passwordFT.getText().length() >= 1){
            if((usenameTF.getText().equals(defaultUsername)) && (passwordFT.getText().equals(defaultPassword))){
              detailObj = new DetailsForm();
              uiObj.dispose();
              Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
               detailObj.setLocation(dim.width/2-300, dim.height/2-200);
               detailObj.setTitle("KeyLogger");
               detailObj.setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "Invalid Login Details", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Enter Username And Password", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_loginBtnActionPerformed

    private void passwordFTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                uiObj = new UI();
                Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
                uiObj.setLocation(dim.width/2-300, dim.height/2-200);
                uiObj.setTitle("KeyLogger");
                uiObj.setVisible(true);
               
            }
        });
    }
    static UI uiObj;
    static DetailsForm detailObj;
    private final String defaultUsername = "admin";
    private final String defaultPassword = "abc123";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel innerWrapper;
    private javax.swing.JButton loginBtn;
    private javax.swing.JLabel loginGif;
    private javax.swing.JLabel loginL;
    private javax.swing.JPanel outerWrapper;
    private javax.swing.JPasswordField passwordFT;
    private javax.swing.JLabel pswdL;
    private javax.swing.JTextField usenameTF;
    private javax.swing.JLabel usernameL;
    // End of variables declaration//GEN-END:variables
}
